# Site settings
title: Corgi Consciousness Calendar
description: Track your corgi's mood with the lunar cycle
baseurl: "/corgi-calendar" # Updated to match GitHub Pages repository name
url: "https://conspiracycorgi.github.io" # Updated to GitHub Pages URL

# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag

# Exclude from processing
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
- .gitignore

