# Site settings
title: Corgi Consciousness Calendar
description: "Track your corgi's mood and behavior patterns with our lunar cycle calendar. Get personalized activity suggestions based on lunar phases."
baseurl: "/corgi-calendar"
url: "https://conspiracycorgi.github.io"
author: ConspiracyCorgi
lang: en
timezone: UTC

# Enhanced SEO settings
twitter:
  username: conspiracycorgi
  card: summary_large_image
logo: /assets/images/corgi-logo.png
social:
  name: Corgi Consciousness Calendar
  links:
    - https://github.com/conspiracycorgi/corgi-calendar
    - https://twitter.com/conspiracycorgi

# Analytics
google_analytics: # Add your Google Analytics ID here

# Additional metadata
keywords: corgi, lunar calendar, pet behavior, moon phases, dog activities
locale: en_US

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

